#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MDPi.Droid.Resource", IsApplication=true)]

namespace MDPi.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PagerSlidingTabStrip.Resource.Attribute.dividerColor = global::MDPi.Droid.Resource.Attribute.dividerColor;
			global::PagerSlidingTabStrip.Resource.Attribute.dividerPadding = global::MDPi.Droid.Resource.Attribute.dividerPadding;
			global::PagerSlidingTabStrip.Resource.Attribute.indicatorColor = global::MDPi.Droid.Resource.Attribute.indicatorColor;
			global::PagerSlidingTabStrip.Resource.Attribute.indicatorHeight = global::MDPi.Droid.Resource.Attribute.indicatorHeight;
			global::PagerSlidingTabStrip.Resource.Attribute.scrollOffset = global::MDPi.Droid.Resource.Attribute.scrollOffset;
			global::PagerSlidingTabStrip.Resource.Attribute.shouldExpand = global::MDPi.Droid.Resource.Attribute.shouldExpand;
			global::PagerSlidingTabStrip.Resource.Attribute.tabBackground = global::MDPi.Droid.Resource.Attribute.tabBackground;
			global::PagerSlidingTabStrip.Resource.Attribute.tabPaddingLeftRight = global::MDPi.Droid.Resource.Attribute.tabPaddingLeftRight;
			global::PagerSlidingTabStrip.Resource.Attribute.textAllCaps = global::MDPi.Droid.Resource.Attribute.textAllCaps;
			global::PagerSlidingTabStrip.Resource.Attribute.underlineColor = global::MDPi.Droid.Resource.Attribute.underlineColor;
			global::PagerSlidingTabStrip.Resource.Attribute.underlineHeight = global::MDPi.Droid.Resource.Attribute.underlineHeight;
			global::PagerSlidingTabStrip.Resource.Color.background_tab_pressed = global::MDPi.Droid.Resource.Color.background_tab_pressed;
			global::PagerSlidingTabStrip.Resource.Drawable.pagerslidingtabstrip_background_tab = global::MDPi.Droid.Resource.Drawable.pagerslidingtabstrip_background_tab;
			global::PagerSlidingTabStrip.Resource.Layout.pagerslidingtabstrip_texttab = global::MDPi.Droid.Resource.Layout.pagerslidingtabstrip_texttab;
			global::PagerSlidingTabStrip.Resource.String.ApplicationName = global::MDPi.Droid.Resource.String.ApplicationName;
			global::PagerSlidingTabStrip.Resource.String.Hello = global::MDPi.Droid.Resource.String.Hello;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip = global::MDPi.Droid.Resource.Styleable.PagerSlidingTabStrip;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_dividerColor = global::MDPi.Droid.Resource.Styleable.PagerSlidingTabStrip_dividerColor;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_dividerPadding = global::MDPi.Droid.Resource.Styleable.PagerSlidingTabStrip_dividerPadding;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_indicatorColor = global::MDPi.Droid.Resource.Styleable.PagerSlidingTabStrip_indicatorColor;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_indicatorHeight = global::MDPi.Droid.Resource.Styleable.PagerSlidingTabStrip_indicatorHeight;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_scrollOffset = global::MDPi.Droid.Resource.Styleable.PagerSlidingTabStrip_scrollOffset;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_shouldExpand = global::MDPi.Droid.Resource.Styleable.PagerSlidingTabStrip_shouldExpand;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_tabBackground = global::MDPi.Droid.Resource.Styleable.PagerSlidingTabStrip_tabBackground;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_tabPaddingLeftRight = global::MDPi.Droid.Resource.Styleable.PagerSlidingTabStrip_tabPaddingLeftRight;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_textAllCaps = global::MDPi.Droid.Resource.Styleable.PagerSlidingTabStrip_textAllCaps;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_underlineColor = global::MDPi.Droid.Resource.Styleable.PagerSlidingTabStrip_underlineColor;
			global::PagerSlidingTabStrip.Resource.Styleable.PagerSlidingTabStrip_underlineHeight = global::MDPi.Droid.Resource.Styleable.PagerSlidingTabStrip_underlineHeight;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000b
			public const int MvxBind = 2130771979;
			
			// aapt resource value: 0x7f01000f
			public const int MvxDropDownItemTemplate = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int MvxItemTemplate = 2130771982;
			
			// aapt resource value: 0x7f01000c
			public const int MvxLang = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int MvxSource = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public const int MvxTemplate = 2130771981;
			
			// aapt resource value: 0x7f010002
			public const int dividerColor = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int dividerPadding = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int indicatorColor = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int indicatorHeight = 2130771971;
			
			// aapt resource value: 0x7f010007
			public const int scrollOffset = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int shouldExpand = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int tabBackground = 2130771976;
			
			// aapt resource value: 0x7f010006
			public const int tabPaddingLeftRight = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int textAllCaps = 2130771978;
			
			// aapt resource value: 0x7f010001
			public const int underlineColor = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int underlineHeight = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int background_tab_pressed = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int card_grey = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int white = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int white_translucent = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_card = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_card_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_card_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monoandroidsplash = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int pagerslidingtabstrip_background_tab = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int ActionBar = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int AnimeList = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int MvxBindingTagUnique = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int addTorrentMenuItem = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int editText_AnimeName = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int indicator = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int pager = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int separator2 = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddTorrentView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BrowseView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FirstView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int item_anime = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int item_menu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int pagerslidingtabstrip_texttab = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SplashScreen = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TorrentsView = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int ActionBar = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int Mono_Android_Theme_Splash = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771981};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771984};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] PagerSlidingTabStrip = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 2
			public const int PagerSlidingTabStrip_dividerColor = 2;
			
			// aapt resource value: 5
			public const int PagerSlidingTabStrip_dividerPadding = 5;
			
			// aapt resource value: 0
			public const int PagerSlidingTabStrip_indicatorColor = 0;
			
			// aapt resource value: 3
			public const int PagerSlidingTabStrip_indicatorHeight = 3;
			
			// aapt resource value: 7
			public const int PagerSlidingTabStrip_scrollOffset = 7;
			
			// aapt resource value: 9
			public const int PagerSlidingTabStrip_shouldExpand = 9;
			
			// aapt resource value: 8
			public const int PagerSlidingTabStrip_tabBackground = 8;
			
			// aapt resource value: 6
			public const int PagerSlidingTabStrip_tabPaddingLeftRight = 6;
			
			// aapt resource value: 10
			public const int PagerSlidingTabStrip_textAllCaps = 10;
			
			// aapt resource value: 1
			public const int PagerSlidingTabStrip_underlineColor = 1;
			
			// aapt resource value: 4
			public const int PagerSlidingTabStrip_underlineHeight = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
