//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDPi.Core.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDPi.Core.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;torrents&quot;: [
        ///	{
        ///		&quot;id&quot;: 2,
        ///		&quot;name&quot;:&quot;Hunter&quot;,
        ///		&quot;hit_regex&quot;:&quot;http:\/\/www.animetake.com\/hunter-x-hunter-2011-episode-(.+?)\/&quot;,
        ///		&quot;dl_regex&quot;:&quot;tid=(\\d+?) \&quot;&gt; \\[\\w+?\\] [\\d\\w;&amp;# ]+? \\d+? \\[720p\\]&quot;,
        ///		&quot;count&quot;: 127
        ///	},
        ///	{
        ///		&quot;id&quot;: 3,
        ///		&quot;name&quot;:&quot;Naruto&quot;,
        ///		&quot;hit_regex&quot;:&quot;http:\/\/www.animetake.com\/naruto-shippuuden-episode-(\\d+?)\/&quot;,
        ///		&quot;dl_regex&quot;:&quot;tid=(\\d+?)[ \&quot;][\\[\\] \\w\\d&amp;#;\\.&gt;&lt;]+\\[720&quot;,
        ///		&quot;count&quot;: 363
        ///	},
        ///	{
        ///		&quot;id&quot;: 3,
        ///		&quot;name&quot;:&quot;Naruto&quot;,
        ///		&quot;hit_regex&quot;:&quot;http:\/\/www.animetake [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ServerQueryTestResult {
            get {
                return ResourceManager.GetString("ServerQueryTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ServerUri {
            get {
                return ResourceManager.GetString("ServerUri", resourceCulture);
            }
        }
    }
}
